app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__="users"
    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(250),index=True)
    email=db.Column(db.String(250),unique=True,index=True)
    pass_secure=db.Column(db.String(255))
    about=db.Column(db.String(500))
    profile=db.Column(db.String(250))
    comments=db.relationship('Comments',backref='user',lazy="dynamic")

    @property
    def password(self):
        raise AttributeError("You cannot read the password attribute")
    @password.setter
    def password(self,password):
        self.pass_secure=generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)



    def __repr__(self):
        return f'User {self.username}'

'''
Pitch ideas table
'''

class Pitches(db.Model):
    __tablename__="pitches"
    id=db.Column(db.Integer,primary_key=True)
    pitch=db.Column(db.String(500))
    title=db.Column(db.String(250))
    author=db.Column(db.String(250))
    categ=db.Column(db.String(250))
    role_id=db.Column(db.Integer,db.ForeignKey('roles.id'))
    def __repr__(self):
        return f'User {self.pitch}'

'''
Comments model
'''
#establishing a database connection
class Comments(db.Model):
    __tablename__='comments'
    id=db.Column(db.Integer,primary_key=True)
    pitch_id=db.Column(db.Integer)
    pitch_title=db.Column(db.String)
    comments=db.Column(db.String)
    posted=db.Column(db.DateTime,default=datetime.utcnow)
    user_id=db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments=Comments.query.filter_by(pitch_id=id).all()
        return comments




class Role(db.Model):
    __tablename__='roles'
    id=db.Column(db.Integer,primary_key=True)
    name=db.Column(db.String(250))
    pitches=db.relationship('Pitches',backref='category',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,TextAreaField,SelectField
from wtforms.validators import Required,Email,EqualTo
from ..models import User
from wtforms import ValidationError

class UpdateProfile(FlaskForm):
    about=TextAreaField("Tell other people about you.",validators=[Required()])
    submit=SubmitField("Submit")


class WritePitch(FlaskForm):
    title=StringField("Title of your Idea",validators=[Required()])
    categ=SelectField("Choose Category",choices=[('c','select'),('AI','Artifitial Intelegence'),('R','Robotics'),('D','Drones'),('IOT','IoT')],validators=[Required()])
    pitch=TextAreaField("In about 200 words Write your Idea",validators=[Required()])
    submit=SubmitField("Submit")

class ReviewForm(FlaskForm):
    title=StringField(" Comment title",validators=[Required()])
    comments=TextAreaField("Comments",validators=[Required()])
    submit=SubmitField("Submit")

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_simplemde import SimpleMDE
from flask_mail import Mail

mail=Mail()
simple=SimpleMDE()
photos=UploadSet('photos',IMAGES)
login_manager=LoginManager()
login_manager.session_protection="strong"
login_manager.login_view="auth.login"
bootstrap=Bootstrap()
db=SQLAlchemy()
def create_app(config_name):
    app=Flask(__name__)

    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    configure_uploads(app,photos)
    simple.init_app(app)
    mail.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app
 

app/main/__init__.py
from flask import Blueprint
main=Blueprint("main",__name__)
from .import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from ..models import User,Pitches,Comments
from . import main
from flask_login import login_required,current_user
from .forms import UpdateProfile,WritePitch,ReviewForm
from .. import db,photos
@main.route("/")
def index():
    title="Pitch"
    message="Home of ideas, Where ideas are born"
    top=Pitches.query.all()
    pitch=Pitches.query.filter_by(categ="AI").all()
    pitch1=Pitches.query.filter_by(categ="R").all()
    pitch2=Pitches.query.filter_by(categ="D").all()
    pitch3=Pitches.query.filter_by(categ="IOT").all()
    top.reverse()
    top_pitch=top[0:4]
    return render_template("index.html",title=title,message=message,pitch=pitch,top_pitch=top_pitch,pitch1=pitch1,pitch2=pitch2,pitch3=pitch3)


@main.route("/user/<uname>")
def profile(uname):
    user=User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    pitch=Pitches.query.filter_by(author=uname).all()
    title=uname
    return render_template("profile/profile.html",user=user,pitch=pitch,title=title)

'''
new Pitch idea
'''

@main.route("/<uname>",methods=["GET","POST"])
@login_required
def new_pitch(uname):
    uname=uname
    user=User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form=WritePitch()
    if form.validate_on_submit():
        new_pitch=Pitches(pitch=form.pitch.data,title=form.title.data,author=uname,categ=form.categ.data)
        db.session.add(new_pitch)
        db.session.commit()
        return redirect(url_for(".index"))


    title="new Pitch"
    return render_template("pitch.html",new_review=form,title=title)

'''
review
'''

@main.route("/pitch/new/review/<int:id>",methods=["GET","POST"])
@login_required
def review(id):
    pitch_id=id
    pitch=Pitches.query.all():
    title="Write a comment"
    form=ReviewForm()
    if form.validate_on_submit():
        title=form.title.data
        comments=form.comments.data

        #update this variables
        review=Comments(pitch_id=id,pitch_title=title,comments=comments,user=current_user)

        #save
        review.save_comment()
        return redirect(url_for('.review',id=pitch_id))

    '''
    query Comments database table
    '''
    all_comments=Comments.query.filter_by(pitch_id=id).all()

    return render_template("new_review.html",pitch=pitch,id=pitch_id,title=title,comment_form=form,all=all_comments)


@main.route("/user/<uname>/update",methods=["GET","POST"])
@login_required
def update_profile(uname):
    user=User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)
    form =UpdateProfile()
    if form.validate_on_submit():
        user.about=form.about.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for(".profile",uname=user.username))

    return render_template("profile/update.html",form=form)

'''
update photos
'''
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile= path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

'''
up down vote
'''

def upVote():
    vote=0:


def downVote():
    pass

app/templates/base.html
{%extends "bootstrap/base.html"%}
{%block navbar%}
  {%include 'navbar.html'%}
{%endblock%}
{%block content%}
{%block styles%}
{{simplemde.css}}
{{simplemde.js}}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/mdb.css')}}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
  <link rel="icon" href="/static/img/ic.png">
  <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.js')}}"></script>
<script src="{{ url_for('static', filename='js/mdb.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script src="{{ url_for('static', filename='js/main.js')}}"></script>

  {%endblock%}

{%endblock%}

app/templates/index.html
{%extends 'base.html'%}


{%block content%}
<div class=" main jumbotron">
  <h1>Welcome to Pitch</h1>
  <h4>{{message}}</h4>
  {%if current_user.is_authenticated%}
  <p>Get started Write your own Idea </p><a href="{{url_for('main.new_pitch',uname=current_user.username)}}"><button class="btn default-color" type="button" name="button">Here</button></a>
  {%else%}
  <p>Get started Write your own Idea </p><a><button class="btn default-color" id="login" type="button" title="Login Required To post your Idea" name="button">Here</button></a>
  {%endif%}
</div>
<div class="container-fluid">
  <div class="row">
    {%for all in top_pitch%}
    <div class="col-md-3">
      <div class="one">
        <div class="on">
          <div  class="jumbotron title">
            <h5>{{all.title}}</h5> <span class="animated fadeIn " aria-hidden="true">New</span>
          </div>
          {{all.pitch}}
          <br>
          <i class="vom">Cetegory {{all.categ}}</i>
          <br>
          <hr class="default-color">
          <a class="btn default-color" href="/pitch/new/review/{{all.id}}">comment</a>
        </div>

      </div>
    </div>
    {%endfor%}

  </div>
  <br>
  <!-- Category Ai starts here-->
  <div class="ai jumbotron">
    <div class="row">
      <div class="col-md-3"><div class="cat card">
        <h1>Artificial intelligence (AI) </h1><hr class="default-color">Category<br><br> <button id="aii" class="btn default-color" type="button" name="button">View Category</button></div>
      </div>
      <div class="col-md-3"> <div class="cat card">
        <h1>Robotics <br>(R)</h1><hr class="default-color">Category<br><br><button id="robot" class="btn default-color" type="button" name="button">View Category</button></div>
      </div>
      <div class="col-md-3"><div class="cat card">
        <h1>Internet of Everything  (IoT)</h1><hr class="default-color">Category<br><br><button id="ot" class="btn default-color" type="button" name="button">View Category</button>
      </div></div>
      <div class="col-md-3"><div class="cat card">
        <h1>Drones  <br>(D)</h1><hr class="default-color">Category<br><br><button id="dro" class="btn default-color" type="button" name="button">View Category</button>
      </div></div>

    </div>
  </div>


  <div id="AI" class="animated fadeIn row">
    <div class="col-md-12">
      <h1>Artificial intelligence (AI) Category</h1>

    </div>
    {%for i in pitch%}
    <div class="col-md-3">
      <div class="one">
        <div class="on">
          <div  class="jumbotron title">
            <h5>{{i.title}}</h5>
          </div>
          {{i.pitch}}
          <hr class="default-color">
          <a class="btn btn-secondary" href="/pitch/new/review/{{i.id}}">comment</a>
        </div>

      </div>

    </div>
    {%endfor%}
  </div>
  <div id="R" class="animated fadeIn row">
    <div class="col-md-12">
      <h1>Robotics  (R) Category</h1>

    </div>
    <div class="container-fluid">
      <div class="row">
        {%for pit in pitch1%}
        <div class="col-md-3">
          <div class="one">
            <div class="on">
              <div  class="jumbotron title">
                <h5>{{pit.title}}</h5>
              </div>
              {{pit.pitch}}
              <hr class="default-color">
              <a class="btn btn-secondary" href="/pitch/new/review/{{pit.id}}">comment</a>
            </div>

          </div>

        </div>

        {%endfor%}
      </div>
    </div>


    </div>

    <!--Robotic-->


<div id="D" class="animated fadeIn row">
  <div class="col-md-12">
    <h1>Drones  (D) Category</h1>

  </div>
  <div class="container-fluid">
    <div class="row">
      {%for i2 in pitch2%}
      <div class="col-md-3">
        <div class="one">
          <div class="on">
            <div  class="jumbotron title">
              <h5>{{i2.title}}</h5>
            </div>
            {{i2.pitch}}
            <hr class="default-color">
            <a class="btn btn-secondary" href="/pitch/new/review/{{i2.id}}">comment</a>
          </div>

        </div>

      </div>

      {%endfor%}
    </div>

  </div>

    </div>

    <!-- IoT-->
    <div id="IoT" class="animated fadeIn row">
      <div class="col-md-12">
        <h1>Internet of Everything  (IoT) Category</h1>
      </div>
      <div class="container-fluid">
        <div class="row">
          {%for i3 in pitch3%}
          <div class="col-md-3">
            <div class="one">
              <div class="on">
                <div  class="jumbotron title">
                  <h5>{{i3.title}}</h5>
                </div>
                {{i3.pitch}}
                <hr class="default-color">
                <a class="btn btn-secondary" href="/pitch/new/review/{{i3.id}}">comment</a>
              </div>

            </div>

          </div>

          {%endfor%}
        </div>
      </div>

  </div>

</div>
<footer class="page-footer font-small bg-default pt-4">

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://github.com/Hano-Guru"> Hanad Ahmed</a>
      </div>
      <!-- Copyright -->

    </footer>



{%endblock%}

app/templates/navbar.html
<nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
  <a class="navbar-brand" href="/">Pitch</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.new_pitch',uname=current_user.username)}}">Post an Idea</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      {% if current_user.is_authenticated%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          {{current_user.username}}<i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
          <a class="dropdown-item" href="{{url_for('auth.logout')}}">Logout</a>
        </div>
      </li>
      {%else%}
      <li class="nav-item">
        <a href="{{url_for('auth.login')}}" class="nav-link waves-effect waves-light">
          <i class="">Sign In</i>
        </a>
      </li>
      {%endif%}
    </ul>
  </div>
</nav>

app/templates/new_review.html
{%extends 'base.html'%}
{%import "bootstrap/wtf.html" as wtf%}
{%block content%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="body">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="">
            <div class="card">
              <h5>This Project was Pitched  by {{pitch[id-1].author}}</h5>
                <h3 class="gnome">Title {{pitch[id-1].title}}</h3>
              <div class="card-body">
                {{pitch[id-1].pitch}}
                <br>
                <hr class="default-color">

                <i>by {{pitch[id-1].author}}</i>
                <button id="like" class="btn btn-success" type="button" name="button"><i class="fas fa-thumbs-up"></i> <p id="p">0</p></button>
                <button id="dislike" class="btn btn-danger" type="button" name="button"><i class="fas fa-thumbs-down"></i><p id="p1">0</p> </button>
              </div>


            </div>
            {%if all%}
            <div class="card">
              <div class="card-body">
                  <h2>Comments.....</h2>
              </div>

            </div>

            {%for come in all%}
            <div class="card">
              <h5>{{come.pitch_title}}</h5>
              <div class="card-body">
               <i class="fas fa-quote-left"> {{come.comments}}</i>
              </div>
              <p>Posted on {{come.posted}}</p>
              <p>posted by {{pitch[id-1].author}}</p>

            </div>

            {%endfor%}
            {%else%}
            <h1 class="animated fadeIn"></h1>
            <div class="card">
              <div class="card-body">
                <h2>No comments yet for this Pitch</h2>
              </div>

            </div>

            {%endif%}


          </div>

        </div>
        <div class="col-md-6">
          <div class="jumbotron">
            <h1>Leave a comment</h1>
            {{wtf.quick_form(comment_form)}}
            
          </div>


        </div>
      </div>

    </div>
    {%endblock%}
  </body>
</html>
<div class="body">

app/templates/pitch.html
{%extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}
{%block content%}
<div id="pitch" class="jumbotron pitch">
  <h1>Write an Idea that will move the world</h1>
  <p><strong><i id="sho">60</i></strong> seconds is all you have</p><button type="button" id="love" class="btn btn-info" name="button">Time yourself</button><span id="show"></span>
  <div id="spinner" class="spinner-grow" role="status">
  <span class="sr-only">Loading...</span>
</div>

</div>
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">

        {{wtf.quick_form(new_review)}}
    </div>
    <div class="col-md-3"></div>

  </div>

</div>
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container-fluid">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <!-- Card -->
<div id="bg"  class="card testimonial-card">

  <!-- Background color -->
  <div class="card-up indigo lighten-1"></div>

  <!-- Avatar -->
  <div class="avatar mx-auto white">
    {% if user.profile %}
    <img src="{{url_for('static',filename=user.profile)}}" alt="profile avatar" class="img-responsive rounded-circle">
    {%else%}
    <img src="/static/img/def.svg" alt="profile avatar" class="img-responsive rounded-circle">
    {% endif %}
  </div>

  <!-- Content -->
  <div class="card-body">
    <!-- Name -->
    <h4 class="card-title">{{user.username| capitalize}}</h4>
    <hr class="default-color">
    <!-- Quotation -->
    <h4>Profile Details</h4>
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
     {% endif %}
    <!--Displaying user bio-->
    {% if user.about %}
      <p><i class="fas fa-quote-left"></i>{{user.about}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

  </div>
  <button id="change" class="btn btn-secondary animated fadeIn" type="button" name="button">Change Profile</button>
<div class="profile animated fadeIn">
  {%if user==current_user%}
  <form class="form-group" action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
    <input class="form-control" type="file" name="photo" value="" required>
    <input  id="update" class="btn btn-info" type="submit" name="" value="Save">
  </form>

  {%endif%}
</div>


</div>
<!-- Card -->



  </div>
  <div class="col-md-8">
    <h1>My pitch Ideas</h1>
    <div class="row">
        {%if pitch%}
        {%for project in pitch%}

      <div class="col-md-6">

        <div class="one">
          <div class="on">
            <div  class="jumbotron title">
              <h5>{{project.title}}</h5>
            </div>
            {{project.pitch}}
            <br>
            <i class="vom">Cetegory {{project.categ}}</i>
            <br>
            <hr class="default-color">
            <a class="btn default-color" href="/pitch/new/review/{{project.id}}">comment</a>
          </div>

        </div>

      </div>

        {%endfor%}
        {%else%}
        <div class="col-md-12">

          <div class="no">

          </div>
          <!-- Card -->
<div class="card card-cascade wider reverse">

  <!-- Card image -->
  <div class="view view-cascade overlay">

      <div class="mask rgba-white-slight"></div>
        <h1>You have No Pitch ideas yet</h1>
  </div>

  <!-- Card content -->
  <div class="card-body card-body-cascade text-center">

    <!-- Title -->
    <h4 class="card-title">Hello {{current_user.username}} <strong>Create your new Amazing Idea </strong></h4>
    <!-- Subtitle -->
    <h6 class="font-weight-bold indigo-text py-2"><a href="{{url_for('main.new_pitch',uname=current_user.username)}}"><button class="btn default-color" type="button" name="button">Get started Here</button></a></h6>

  </div>

</div>
<!-- Card -->

        </div>

        {%endif%}



    </div>


  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}